presentation:
  title: 'Stop Fighting Wraparound: Embed Your Rings!'
  subtitle: The One Math Trick That Fixes Circular Quantity Bugs
  author: Geoff
  date: '2025-09-09'
  venue: CeresTalk
slides:
- 01-title.html
- 02-the-bug.html
- 03-midnight-bug.html
- 11-interactive-demo.html
- 05-robot-heading.html
- 06-color-interpolation.html
- 15-other-circular-quantities.html
- 12-gis-demo.html
- 16-arbitrary-wrap-points.html
- 07-general-pattern.html
- 08-mathematical-insight.html
- 04-the-solution.html
- 13-circular-statistics.html
- 14-discrete-calculus.html
- 18-flight-photo-window.html
- 09-takeaways.html
- 10-questions.html
build:
  single_file: true
  bundle_folder: true
  webp_quality: 90
  max_image_width: 1920
  compress_json: true
colors:
  navy_dark: '#0A3D82'
  navy_medium: '#1B4A8C'
  cream: '#F5F0E6'
  red: '#E53935'
  gold: '#FFC107'
  bg_primary: '#0A3D82'
  bg_secondary: '#1B4A8C'
  text_primary: '#F5F0E6'
  text_secondary: '#B8C5D6'
  text_muted: '#8A9BAE'
  card_bg: rgba(10, 61, 130, 0.1)
  card_border: '#FFC107'
  code_bg: rgba(0, 0, 0, 0.5)
  code_text: '#F5F0E6'
  success: '#FFC107'
  warning: '#FF6B35'
  error: '#E53935'
  info: '#B8C5D6'
  white_5: rgba(245, 240, 230, 0.05)
  white_10: rgba(245, 240, 230, 0.1)
  white_15: rgba(245, 240, 230, 0.15)
  navy_10: rgba(10, 61, 130, 0.1)
  navy_20: rgba(10, 61, 130, 0.2)
  gold_20: rgba(255, 193, 7, 0.2)
  red_20: rgba(229, 57, 53, 0.2)
